config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'timecards#new'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :edit, :update, :destroy]
  
  resources :year_months, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'to_show'
      get 'total'
    end
  end

  get 'user/:user_id/year_month/:id', to: 'year_months#manage'
  get 'user/:user_id/year_month/:id/to_manage', to: 'year_months#to_manage'

  get 'requests', to: 'requests#index'

  resources :day do
    resources :pending_timecards, only: [:new, :create]
    resources :pending_schedules, only: [:new, :create]
  end

  get 'user/:user_id/day/:day_id/edit_timecard', to: 'timecards#edit'
  get 'user/:user_id/day/:day_id/edit_schedule', to: 'schedules#edit'

  get 'user/:user_id/day/:day_id/update_timecard', to: 'timecards#update'
  get 'user/:user_id/day/:day_id/update_schedule', to: 'schedules#update'

  resources :pending_timecards, only: [:update, :destroy] do
    member do
      patch 'permission'
    end
  end

  resources :pending_schedules, only: [:update, :destroy] do
    member do
      patch 'permission'
    end
  end

  get 'permissions', to: 'permissions#index'

  resources :timecards, only: [:index, :new, :create] do
    collection do
      post 'create_start'
      post 'create_finish'
      post 'create_break_start'
      post 'create_break_finish'
    end
    member do
      patch 'update_start'
      patch 'update_finish'
      patch 'update_break_start'
      patch 'update_break_finish'
    end
  end

  get 'setting', to: 'settings#setting'

  resources :commutes, only: [:new, :create]

  get 'commute/:user_id', to: 'commutes#edit'
  get 'commute/:user_id/update', to: 'commutes#update'

  resources :travel_costs, only: [:destroy] do
    collection do
      post 'create_car'
      post 'create_train'
      post 'create_pass'
      post 'create_walk'
      post 'create_trip'
      post 'create_remote'
      post 'create_other'
    end
  end

  get 'travel_cost/index/:user_id/:year_month_id', to: 'travel_costs#index'
  get 'travel_cost/index/:user_id/:year_month_id/to_index', to: 'travel_costs#to_index'

  get 'travel_cost/edit/:user_id/:day_id', to: 'travel_costs#edit'

  get 'travel_cost/update_car/:user_id/:day_id', to: 'travel_costs#update_car'
  get 'travel_cost/update_train/:user_id/:day_id', to: 'travel_costs#update_train'
  get 'travel_cost/update_pass/:user_id/:day_id', to: 'travel_costs#update_pass'
  get 'travel_cost/update_walk/:user_id/:day_id', to: 'travel_costs#update_walk'
  get 'travel_cost/update_trip/:user_id/:day_id', to: 'travel_costs#update_trip'
  get 'travel_cost/update_remote/:user_id/:day_id', to: 'travel_costs#update_remote'
  get 'travel_cost/update_other/:user_id/:day_id', to: 'travel_costs#update_other'
  
end

app/models/timecard.rb
class Timecard < ApplicationRecord
  belongs_to :user
  belongs_to :day
  has_many :pending_timecards, dependent: :destroy

end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController

  def index
    @users = User.where.not(user_type: "管理者")
    @days = Day.where(date: ...Date.today)
  end

  def new
    @timecard = Timecard.where(user_id: current_user.id).where(day_id: Day.find_by(date: Date.today).id)
    @days = Day.where(date: ...Date.today)
    @pending_timecards = PendingTimecard.where(updated_at: 1.day.ago..).where(timecard_id: Timecard.where(user_id: current_user.id).ids)
    @pending_schedules = PendingSchedule.where(updated_at: 1.day.ago..).where(schedule_id: Schedule.where(user_id: current_user.id).ids)
    @waiting_pending_timecards = PendingTimecard.where(status: "未承認")
    @waiting_pending_schedules = PendingSchedule.where(status: "未承認")
    @pending_timecards_member = PendingTimecard.where(timecard_id: Timecard.where(user_id: User.where(approver_id: current_user.id).ids).ids).where(status: "未承認")
    @pending_schedules_member = PendingSchedule.where(schedule_id: Schedule.where(user_id: User.where(approver_id: current_user.id).ids).ids).where(status: "未承認")
    @members = User.where(approver_id: current_user.id)
    @users = User.where.not(user_type: "管理者")
  end

  def create_start
    timecard = Timecard.find_or_initialize_by(user_id: current_user.id, day_id: Day.find_by(date: Date.today).id)
    if timecard.new_record?
      timecard.start = Time.now.change(sec: 00)
      timecard.save
    else
      timecard.update_attribute(:start, Time.now.change(sec: 00))
    end
    redirect_to new_timecard_path, notice: "打刻しました - 出勤"
  end

  def create_finish
    timecard = Timecard.find_or_initialize_by(user_id: current_user.id, day_id: Day.find_by(date: Date.today).id)
    if timecard.new_record?
      timecard.finish = Time.now.change(sec: 00)
      timecard.save
    else
      timecard.update_attribute(:finish, Time.now.change(sec: 00))
    end
    redirect_to new_timecard_path, notice: "打刻しました - 退勤"
  end

  def create_break_start
    timecard = Timecard.find_or_initialize_by(user_id: current_user.id, day_id: Day.find_by(date: Date.today).id)
    if timecard.new_record?
      timecard.break_start = Time.now.change(sec: 00)
      timecard.save
    else
      timecard.update_attribute(:break_start, Time.now.change(sec: 00))
    end
    redirect_to new_timecard_path, notice: "打刻しました - 休憩開始"
  end

  def create_break_finish
    timecard = Timecard.find_or_initialize_by(user_id: current_user.id, day_id: Day.find_by(date: Date.today).id)
    if timecard.new_record?
      timecard.break_finish = Time.now.change(sec: 00)
      timecard.save
    else
      timecard.update_attribute(:break_finish, Time.now.change(sec: 00))
    end
    redirect_to new_timecard_path, notice: "打刻しました - 休憩終了"
  end
  
  def edit
    @day = Day.find(params[:day_id])
    @timecard = Timecard.where(day_id: params[:day_id]).find_by(user_id: params[:user_id])
    @timecard_new = Timecard.new
  end

  def update
    timecard = Timecard.find_or_initialize_by(day_id: params[:day_id], user_id: params[:user_id])
    if timecard.new_record?
      timecard = Timecard.new(timecard_update_params)
      timecard.save
    else
      timecard.update(timecard_update_params)
    end
    redirect_to "/user/#{params[:user_id]}/year_month/#{Day.find(params[:day_id]).year_month_id}", notice: "打刻編集を保存しました"
  end

  private

  def timecard_params
    params.require(:timecard).permit(:start, :finish, :break_start, :break_finish).merge(user_id: current_user.id, day_id: DAY.find_by(date: Date.today).id)
  end

  def timecard_update_params
    params.require(:timecard).permit(:start, :finish, :break_start, :break_finish).merge(user_id: params[:user_id], day_id: params[:day_id])
  end
end

app/helpers/timecards_helper.rb
module TimecardsHelper
end

app/views/timecards/edit.html.erb
<% day = ["日","月","火","水","木","金","土"] %>

<%= render "shared/flash" %>
<%= render "shared/header_common" %>

<div class="timecard-edit-wrapper" >

  <h2><i class="far fa-clock"></i> 打刻編集</h2>

  <h3><%= @day.date.strftime("%Y/%m/%d") %>(<%= day[@day.date.wday] %>)</h3>
  <h3>■現在の打刻</h3>
  <table>
    <thead>
      <th>出勤</th>
      <th>退勤</th>
      <th>休憩開始</th>
      <th>休憩終了</th>
    </thead>
    <tr>
      <% if @timecard %>
        <% if @timecard.start %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "出勤",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "出勤",status: "未承認").pending_time.present? %>
              <th><%= @timecard.start.strftime("%R") %><br>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "出勤",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th><%= @timecard.start.strftime("%R") %><br>(--:--)</th>
            <% end %>
          <% else %>
            <th><%= @timecard.start.strftime("%R") %></th>
          <% end %>
        <% else %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "出勤",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "出勤",status: "未承認").pending_time.present? %>
              <th>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "出勤",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th>(--:--)</th>
            <% end %>
          <% else %>
            <th>--:--</th>
          <% end %>
        <% end %>
        <% if @timecard.finish %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "退勤",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "退勤",status: "未承認").pending_time.present? %>
              <th><%= @timecard.finish.strftime("%R") %><br>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "退勤",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th><%= @timecard.finish.strftime("%R") %><br>(--:--)</th>
            <% end %>
          <% else %>
            <th><%= @timecard.finish.strftime("%R") %></th>
          <% end %>
        <% else %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "退勤",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "退勤",status: "未承認").pending_time.present? %>
              <th>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "退勤",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th>(--:--)</th>
            <% end %>
          <% else %>
            <th>--:--</th>
          <% end %>
        <% end %>
        <% if @timecard.break_start %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩開始",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩開始",status: "未承認").pending_time.present? %>
              <th><%= @timecard.break_start.strftime("%R") %><br>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩開始",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th><%= @timecard.break_start.strftime("%R") %><br>(--:--)</th>
            <% end %>
          <% else %>
            <th><%= @timecard.break_start.strftime("%R") %></th>
          <% end %>
        <% else %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩開始",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩開始",status: "未承認").pending_time.present? %>
              <th>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩開始",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th>(--:--)</th>
            <% end %>
          <% else %>
            <th>--:--</th>
          <% end %>
        <% end %>
        <% if @timecard.break_finish %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩終了",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩終了",status: "未承認").pending_time.present? %>
              <th><%= @timecard.break_finish.strftime("%R") %><br>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩終了",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th><%= @timecard.break_finish.strftime("%R") %><br>(--:--)</th>
            <% end %>
          <% else %>
            <th><%= @timecard.break_finish.strftime("%R") %></th>
          <% end %>
        <% else %>
          <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩終了",status: "未承認") %>
            <% if PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩終了",status: "未承認").pending_time.present? %>
              <th>(<%= PendingTimecard.find_by(timecard_id: @timecard.id, timecard_type: "休憩終了",status: "未承認").pending_time.strftime("%R") %>)</th>
            <% else %>
              <th>(--:--)</th>
            <% end %>
          <% else %>
            <th>--:--</th>
          <% end %>
        <% end %>
      <% else %>
        <th>--:--</th><th>--:--</th><th>--:--</th><th>--:--</th>
      <% end %>
    </tr>
  </table>

  <h3>■打刻編集</h3>
  <% if @timecard %>
    <%= form_with model: @timecard, url: "/user/#{params[:user_id]}/day/#{params[:day_id]}/update_timecard", method: :get do |form| %>
      <div>
        <%= form.label :start, "出勤：" %>
        <%= form.time_field :start %>
      </div>
      <div>
        <%= form.label :finish, "退勤：" %>
        <%= form.time_field :finish %>
      </div>
      <div>
        <%= form.label :break_start, "休憩開始：" %>
        <%= form.time_field :break_start %>
      </div>
      <div>
        <%= form.label :break_finish, "休憩終了：" %>
        <%= form.time_field :break_finish %>
      </div>
      <div>
        <%= form.submit "保存" %>
      </div>
    <% end %>
  <% else %>
    <%= form_with model: @timecard_new, url: "/user/#{params[:user_id]}/day/#{params[:day_id]}/update_timecard", method: :get do |form| %>
      <div>
        <%= form.label :start, "出勤：" %>
        <%= form.time_field :start %>
      </div>
      <div>
        <%= form.label :finish, "退勤：" %>
        <%= form.time_field :finish %>
      </div>
      <div>
        <%= form.label :break_start, "休憩開始：" %>
        <%= form.time_field :break_start %>
      </div>
      <div>
        <%= form.label :break_finish, "休憩終了：" %>
        <%= form.time_field :break_finish %>
      </div>
      <div>
        <%= form.submit "保存" %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/timecards/index.html.erb
<%# /timecards 上長・管理者用メンバー一覧ページ %>

<% if current_user.user_type == "上長" %>
  <% @users = @users.where(approver_id: current_user.id) %>
<% end %>

<%= render "shared/flash" %>
<%= render "shared/header_common" %>

<div class="timecards-wrapper">

  <h2><i class="fas fa-user-friends"></i> メンバー</h2>

  <% if current_user.user_type == "上長" %>
    <% @users = @users.where(approver_id: current_user.id) %>

    <% @users.each do |m| %>

      <div class="timecards-user">
        <span><%= m.full_name %></span>
        <%= link_to "/user/#{m.id}/year_month/#{Day.find_by(date: Date.today).year_month_id}" do %>
          <i class="far fa-calendar-alt"></i>
          <% if m.timecard_error %>
            <i class="fas fa-exclamation-triangle"></i>
          <% end %>
        <% end %>
        <%= link_to "/travel_cost/index/#{m.id}/#{Day.find_by(date: Date.today).year_month_id}" do %>
          <i class="fas fa-yen-sign"></i>
          <% if m.travel_cost_error %>
            <i class="fas fa-exclamation-triangle"></i>
          <% end %>
        <% end %>
      </div>

    <% end %>

  <% elsif current_user.user_type == "管理者" %>
    <div class="timecards-department">
      <h3>■営業部</h3>
      <% @users.where(department: "営業部").each do |m| %>

        <div class="timecards-user">
          <span><%= m.full_name %></span>
          <%= link_to "/user/#{m.id}/year_month/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="far fa-calendar-alt"></i>
            <% if m.timecard_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
          <%= link_to "/travel_cost/index/#{m.id}/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="fas fa-yen-sign"></i>
            <% if m.travel_cost_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
        </div>

      <% end %>
    </div>

    <div class="timecards-department">
      <h3>■貿易部</h3>
      <% @users.where(department: "貿易部").each do |m| %>

        <div class="timecards-user">
          <span><%= m.full_name %></span>
          <%= link_to "/user/#{m.id}/year_month/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="far fa-calendar-alt"></i>
            <% if m.timecard_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
          <%= link_to "/travel_cost/index/#{m.id}/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="fas fa-yen-sign"></i>
            <% if m.travel_cost_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
        </div>

      <% end %>
    </div>

    <div class="timecards-department">
      <h3>■システム部</h3>
      <% @users.where(department: "システム部").each do |m| %>

        <div class="timecards-user">
          <span><%= m.full_name %></span>
          <%= link_to "/user/#{m.id}/year_month/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="far fa-calendar-alt"></i>
            <% if m.timecard_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
          <%= link_to "/travel_cost/index/#{m.id}/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="fas fa-yen-sign"></i>
            <% if m.travel_cost_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
        </div>
        
      <% end %>
    </div>

    <div class="timecards-department">
      <h3>■その他</h3>
      <% @users.where(department: "その他").each do |m| %>
      
        <div class="timecards-user">
          <span><%= m.full_name %></span>
          <%= link_to "/user/#{m.id}/year_month/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="far fa-calendar-alt"></i>
            <% if m.timecard_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
          <%= link_to "/travel_cost/index/#{m.id}/#{Day.find_by(date: Date.today).year_month_id}" do %>
            <i class="fas fa-yen-sign"></i>
            <% if m.travel_cost_error %>
              <i class="fas fa-exclamation-triangle"></i>
            <% end %>
          <% end %>
        </div>

      <% end %>
    </div>
  <% end %>
</div>

app/views/timecards/new.html.erb
<%= render "shared/flash" %>
<%= render "shared/header_common" %>


<% if current_user.user_type == "一般" || current_user.user_type == "上長" %>
  <div class="stamping-wrapper">
    <div class="clock-outer">
      <div id="clock-date"></div>
      <div id="clock-time"></div>
    </div>
    <div class="stamping">
      <section>
        <%= link_to create_start_timecards_path, method: :post, class: "btn btn-border btn-start" do %>
          <span><i class="fas fa-sun"></i>出勤</span>
        <% end %>
      </section>
      <section>
        <%= link_to create_finish_timecards_path, method: :post, class: "btn btn-border btn-finish" do %>
          <span><i class="fas fa-moon"></i>退勤</span>
        <% end %>
      </section>
    </div>
    <div class="stamping">
      <section>
        <%= link_to create_break_start_timecards_path, method: :post, class: "btn btn-border btn-break_start" do %>
          <span><i class="fas fa-coffee"></i>休憩開始</span>
        <% end %>
      </section>
      <section>
        <%= link_to create_break_finish_timecards_path, method: :post, class: "btn btn-border btn-break_finish" do %>
          <span><i class="fas fa-coffee"></i>休憩終了</span>
        <% end %>
      </section>
    </div>
  </div>
<% elsif current_user.user_type == "管理者" %>
  <br>
  <%# <div class="top-administrator-links">
    <%= link_to "#" do %>
      <%# <div class="admin-link">
        <i class="fas fa-calendar-day"></i>
      </div>
    <% end %>
    <%# <%= link_to "#" do %>
      <%# <div class="admin-link">
        <i class="fas fa-calendar-alt"></i>
      </div>
    <% end %>
    <%# <%= link_to "#" do %>
      <%# <div class="admin-link">
        <i class="fas fa-book"></i>
      </div>
    <% end %>
  <%# </div>
  <div class="admin-link-title">
    <span>日別データ</span>
    <span>月別データ</span>
    <span>年別データ</span>
  </div> %>
<% end %>

<% if current_user.user_type != "管理者" %>

  <div class="travel-cost-wrapper">
    <div class="travel-cost-inner">
      <% if current_user.commute && current_user.commute.car_type.present? %>
        <section class="balloon-hover">
          <%= link_to create_car_travel_costs_path, method: :post, class: "btn btn-border travel-cost-btn" do %>
            <span><i class="fas fa-car-side"></i></span>
          <% end %>
          <p class="balloon">車・バイク</p>
        </section>
      <% end %>
      <% if current_user.commute && current_user.commute.train_route.present? %>
        <section class="balloon-hover">
          <%= link_to create_train_travel_costs_path, method: :post, class: "btn btn-border travel-cost-btn" do %>
            <span><i class="fas fa-subway"></i></span>
          <% end %>
          <p class="balloon">電車・バス（往復）</p>
        </section>
      <% end %>
      <% if current_user.commute && current_user.commute.pass_route.present? %>
        <section class="balloon-hover">
          <%= link_to create_pass_travel_costs_path, method: :post, class: "btn btn-border travel-cost-btn" do %>
            <span><i class="fas fa-ticket-alt"></i></span>
          <% end %>
          <p class="balloon">電車・バス（定期使用）</p>
        </section>
      <% end %>
      <% if current_user.commute && current_user.commute.walk %>
        <section class="balloon-hover">
          <%= link_to create_walk_travel_costs_path, method: :post, class: "btn btn-border travel-cost-btn" do %>
            <span><i class="fas fa-walking"></i></span>
          <% end %>
          <p class="balloon">徒歩</p>
        </section>
      <% end %>
      <section class="balloon-hover">
        <%= link_to create_trip_travel_costs_path, method: :post, class: "btn btn-border travel-cost-btn" do %>
          <span><i class="fas fa-briefcase"></i></span>
        <% end %>
        <p class="balloon">出張</p>
      </section>
      <section class="balloon-hover">
        <%= link_to create_remote_travel_costs_path, method: :post, class: "btn btn-border travel-cost-btn" do %>
          <span><i class="fas fa-home"></i></span>
        <% end %>
        <p class="balloon">リモートワーク</p>
      </section>
      <section class="hidden balloon-hover">
        <label class="btn btn-border travel-cost-btn hidden-form-btn acd-label" for="acd-check1">
          <span><i class="fas fa-question"></i></span>
        </label>
        <p class="balloon">その他</p>
      </section>
    </div>
    <input type="checkbox" class="acd-check" id="acd-check1"/>
    <div class="acd-content">
      <% if TravelCost.find_by(user_id: current_user.id, day_id: Day.find_by(date: Date.today).id) %>
        <% tc = TravelCost.find_by(user_id: current_user.id, day_id: Day.find_by(date: Date.today).id) %>
      <% else %>
        <% tc = TravelCost.new %>
      <% end %>
      <%= form_with model: tc, url: create_other_travel_costs_path, method: :post do |f| %>
        <span><i class="fas fa-question"></i> その他通勤手段</span>
        <br>
        <span>※簡潔に入力してください</span>
        <br>
        <%= f.label :commute_type, "手段：" %>
        <%= f.text_field :commute_type %><span>　</span>
        <br>
        <%= f.label :remark, "経路：" %>
        <%= f.text_field :remark %><span>　</span>
        <br>
        <%= f.label :travel_cost, "費用：" %>
        <%= f.number_field :travel_cost %><span>円</span>
        <br>
        <%= f.submit "登録" %>
      <% end %>
    </div>
  </div>

<% end %>

<div class="alert-wrapper">
  <div class="alert-title">
    <span>アラート一覧</span>
  </div>
  <div class="alert-link">
    <%= render "shared/alert_common" %>
  </div>
</div>