config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'timecards#new'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :edit, :update, :destroy]
  
  resources :year_months, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'to_show'
      get 'total'
    end
  end

  get 'user/:user_id/year_month/:id', to: 'year_months#manage'
  get 'user/:user_id/year_month/:id/to_manage', to: 'year_months#to_manage'

  get 'requests', to: 'requests#index'

  resources :day do
    resources :pending_timecards, only: [:new, :create]
    resources :pending_schedules, only: [:new, :create]
  end

  get 'user/:user_id/day/:day_id/edit_timecard', to: 'timecards#edit'
  get 'user/:user_id/day/:day_id/edit_schedule', to: 'schedules#edit'

  get 'user/:user_id/day/:day_id/update_timecard', to: 'timecards#update'
  get 'user/:user_id/day/:day_id/update_schedule', to: 'schedules#update'

  resources :pending_timecards, only: [:update, :destroy] do
    member do
      patch 'permission'
    end
  end

  resources :pending_schedules, only: [:update, :destroy] do
    member do
      patch 'permission'
    end
  end

  get 'permissions', to: 'permissions#index'

  resources :timecards, only: [:index, :new, :create] do
    collection do
      post 'create_start'
      post 'create_finish'
      post 'create_break_start'
      post 'create_break_finish'
    end
    member do
      patch 'update_start'
      patch 'update_finish'
      patch 'update_break_start'
      patch 'update_break_finish'
    end
  end

  get 'setting', to: 'settings#setting'

  resources :commutes, only: [:new, :create]

  get 'commute/:user_id', to: 'commutes#edit'
  get 'commute/:user_id/update', to: 'commutes#update'

  resources :travel_costs, only: [:destroy] do
    collection do
      post 'create_car'
      post 'create_train'
      post 'create_pass'
      post 'create_walk'
      post 'create_trip'
      post 'create_remote'
      post 'create_other'
    end
  end

  get 'travel_cost/index/:user_id/:year_month_id', to: 'travel_costs#index'
  get 'travel_cost/index/:user_id/:year_month_id/to_index', to: 'travel_costs#to_index'

  get 'travel_cost/edit/:user_id/:day_id', to: 'travel_costs#edit'

  get 'travel_cost/update_car/:user_id/:day_id', to: 'travel_costs#update_car'
  get 'travel_cost/update_train/:user_id/:day_id', to: 'travel_costs#update_train'
  get 'travel_cost/update_pass/:user_id/:day_id', to: 'travel_costs#update_pass'
  get 'travel_cost/update_walk/:user_id/:day_id', to: 'travel_costs#update_walk'
  get 'travel_cost/update_trip/:user_id/:day_id', to: 'travel_costs#update_trip'
  get 'travel_cost/update_remote/:user_id/:day_id', to: 'travel_costs#update_remote'
  get 'travel_cost/update_other/:user_id/:day_id', to: 'travel_costs#update_other'
  
end

app/views/shared/_flash.html.erb
<div class="flash notice"><%= notice %></div>
<div class="flash alert"><%= alert %></div>

app/views/shared/_header_common.html.erb
<header class="header-common">
  <% if user_signed_in? %>
    <div class="header-left">
      <span><%= current_user.department %>　</span>
      <span><%= current_user.last_name + " " + current_user.first_name %></span>
    </div>
    <div class="header-right">
      <% if current_user.user_type == "一般" %>
        <%= link_to new_timecard_path do %>
          <i class="fas fa-home"></i>
        <% end %>
        <%= link_to "/year_months/#{Day.find_by(date: Date.today).year_month_id}" do %>
          <i class="far fa-calendar-alt"></i>
        <% end %>
        <%= link_to requests_path do %>
          <i class="far fa-list-alt"></i>
        <% end %>
        <%= link_to "/travel_cost/index/#{current_user.id}/#{Day.find_by(date: Date.today).year_month_id}" do %>
          <i class="fas fa-yen-sign"></i>
        <% end %>
        <%= link_to setting_path do %>
          <i class="fas fa-cog"></i>
        <% end %>
      <% elsif current_user.user_type == "上長" %>
        <%= link_to new_timecard_path do %>
          <i class="fas fa-home"></i>
        <% end %>
        <%= link_to "/year_months/#{Day.find_by(date: Date.today).year_month_id}" do %>
          <i class="far fa-calendar-alt"></i>
        <% end %>
        <%= link_to "/travel_cost/index/#{current_user.id}/#{Day.find_by(date: Date.today).year_month_id}" do %>
          <i class="fas fa-yen-sign"></i>
        <% end %>
        <%= link_to timecards_path do %>
          <i class="fas fa-user-friends"></i>
        <% end %>
        <%= link_to permissions_path, data: { turbolinks: false } do %>
          <i class="far fa-check-square"></i>
        <% end %>
        <%# <%= link_to "#" do %>
          <%# <i class="fas fa-chart-bar"></i>
        <% end %>
        <%= link_to setting_path do %>
          <i class="fas fa-cog"></i>
        <% end %>
      <% elsif current_user.user_type == "管理者" %>
        <%= link_to new_timecard_path do %>
          <i class="fas fa-home"></i>
        <% end %>
        <%= link_to timecards_path do %>
          <i class="fas fa-user-friends"></i>
        <% end %>
        <%= link_to permissions_path, data: { turbolinks: false } do %>
          <i class="far fa-check-square"></i>
        <% end %>
        <%# <%= link_to "#" do %>
          <%# <i class="fas fa-chart-bar"></i>
        <% end %>
        <%= link_to setting_path do %>
          <i class="fas fa-cog"></i>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="header-left">
      <span>ログインしていません</span>
    </div>
    <div class="header-right">
      <span>ログインしていません</span>
    </div>
  <% end %>
</header>

<div class="header-space">
</div>