config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'timecards#new'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :edit, :update, :destroy]
  
  resources :year_months, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'to_show'
      get 'total'
    end
  end

  get 'user/:user_id/year_month/:id', to: 'year_months#manage'
  get 'user/:user_id/year_month/:id/to_manage', to: 'year_months#to_manage'

  get 'requests', to: 'requests#index'

  resources :day do
    resources :pending_timecards, only: [:new, :create]
    resources :pending_schedules, only: [:new, :create]
  end

  get 'user/:user_id/day/:day_id/edit_timecard', to: 'timecards#edit'
  get 'user/:user_id/day/:day_id/edit_schedule', to: 'schedules#edit'

  get 'user/:user_id/day/:day_id/update_timecard', to: 'timecards#update'
  get 'user/:user_id/day/:day_id/update_schedule', to: 'schedules#update'

  resources :pending_timecards, only: [:update, :destroy] do
    member do
      patch 'permission'
    end
  end

  resources :pending_schedules, only: [:update, :destroy] do
    member do
      patch 'permission'
    end
  end

  get 'permissions', to: 'permissions#index'

  resources :timecards, only: [:index, :new, :create] do
    collection do
      post 'create_start'
      post 'create_finish'
      post 'create_break_start'
      post 'create_break_finish'
    end
    member do
      patch 'update_start'
      patch 'update_finish'
      patch 'update_break_start'
      patch 'update_break_finish'
    end
  end

  get 'setting', to: 'settings#setting'

  resources :commutes, only: [:new, :create]

  get 'commute/:user_id', to: 'commutes#edit'
  get 'commute/:user_id/update', to: 'commutes#update'

  resources :travel_costs, only: [:destroy] do
    collection do
      post 'create_car'
      post 'create_train'
      post 'create_pass'
      post 'create_walk'
      post 'create_trip'
      post 'create_remote'
      post 'create_other'
    end
  end

  get 'travel_cost/index/:user_id/:year_month_id', to: 'travel_costs#index'
  get 'travel_cost/index/:user_id/:year_month_id/to_index', to: 'travel_costs#to_index'

  get 'travel_cost/edit/:user_id/:day_id', to: 'travel_costs#edit'

  get 'travel_cost/update_car/:user_id/:day_id', to: 'travel_costs#update_car'
  get 'travel_cost/update_train/:user_id/:day_id', to: 'travel_costs#update_train'
  get 'travel_cost/update_pass/:user_id/:day_id', to: 'travel_costs#update_pass'
  get 'travel_cost/update_walk/:user_id/:day_id', to: 'travel_costs#update_walk'
  get 'travel_cost/update_trip/:user_id/:day_id', to: 'travel_costs#update_trip'
  get 'travel_cost/update_remote/:user_id/:day_id', to: 'travel_costs#update_remote'
  get 'travel_cost/update_other/:user_id/:day_id', to: 'travel_costs#update_other'
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @pending_timecards = PendingTimecard.where(timecard_id: Timecard.where(user_id: current_user.id).ids)
    @pending_schedules = PendingSchedule.where(schedule_id: Schedule.where(user_id: current_user.id).ids)
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/index.html.erb
<% day = ["日","月","火","水","木","金","土"] %>

<%= render "shared/flash" %>
<%= render "shared/header_common" %>

<div class="requests-wrapper">

  <h2><i class="far fa-list-alt"></i> 申請一覧（個人）</h2>
  <h3>未承認の申請</h3>

  <p>■打刻申請</p>
  <% if @pending_timecards.exists?(status: "未承認") %>
    <table>
      <thead>
        <th>申請日</th>
        <th>対象日</th>
        <th>打刻種別</th>
        <th>申請元の打刻</th>
        <th>申請された打刻</th>
        <th>申請者メッセージ</th>
        <th>キャンセル</th>
      </thead>
        <% @pending_timecards.each do |pt| %>
          <tr>
            <% if pt.status == "未承認" %>
              <td><%= pt.created_at.strftime("%m/%d") %>(<%= day[pt.created_at.wday] %>)</td>
              <td><%= Day.find_by(id: Timecard.find_by(id: pt.timecard_id).day_id).date.strftime("%m/%d") %>(<%= day[Day.find_by(id: Timecard.find_by(id: pt.timecard_id).day_id).date.wday] %>)</td>
              <td><%= pt.timecard_type %></td>
              <% if pt.timecard_type == "出勤" %>
                <% if Timecard.find_by(id: pt.timecard_id).start.present? %>
                  <td><%= Timecard.find_by(id: pt.timecard_id).start.strftime("%R") %></td>
                <% else %>
                  <td>--:--</td>
                <% end %>
              <% elsif pt.timecard_type == "退勤" %>
                <% if Timecard.find_by(id: pt.timecard_id).finish.present? %>
                  <td><%= Timecard.find_by(id: pt.timecard_id).finish.strftime("%R") %></td>
                <% else %>
                  <td>--:--</td>
                <% end %>
              <% elsif pt.timecard_type == "休憩開始" %>
                <% if Timecard.find_by(id: pt.timecard_id).break_start.present? %>
                  <td><%= Timecard.find_by(id: pt.timecard_id).break_start.strftime("%R") %></td>
                <% else %>
                  <td>--:--</td>
                <% end %>
              <% elsif pt.timecard_type == "休憩終了" %>
                <% if Timecard.find_by(id: pt.timecard_id).break_finish.present? %>
                  <td><%= Timecard.find_by(id: pt.timecard_id).break_finish.strftime("%R") %></td>
                <% else %>
                  <td>--:--</td>
                <% end %>
              <% end %>
              <% if pt.pending_time.present? %>
                <td><%= pt.pending_time.strftime("%R") %></td>
              <% else %>
                <td>--:--</td>
              <% end %>
              <% if pt.comment_request.present? %>
                <td><%= pt.comment_request %></td>
              <% else %>
                <td>-</td>
              <% end %>
              <td>
                <%= link_to pending_timecard_path(pt.id), method: :delete do %>
                  <i class="fas fa-trash-alt fa-lg"></i>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
    </table>
  <% else %>
    <p>未承認の打刻申請はありません</p>
  <% end %>

  <br>
  <p>■日程申請</p>
  <% if @pending_schedules.exists?(status: "未承認") %>
    <table>
      <thead>
        <th>申請日</th>
        <th>対象日</th>
        <th>申請元の日程</th>
        <th>申請された日程</th>
        <th>申請者メッセージ</th>
        <th>キャンセル</th>
      </thead>
      <% @pending_schedules.each do |ps| %>
        <% if ps.status == "未承認" %>
          <tr>
            <td><%= ps.created_at.strftime("%m/%d") %>(<%= day[ps.created_at.wday] %>)</td>
            <td><%= Day.find_by(id: Schedule.find_by(id: ps.schedule_id).day_id).date.strftime("%m/%d") %>(<%= day[Day.find_by(id: Schedule.find_by(id: ps.schedule_id).day_id).date.wday] %>)</td>
            <% if Schedule.find_by(id: ps.schedule_id).schedule_type.present? %>
              <td><%= Schedule.find_by(id: ps.schedule_id).schedule_type %></td>
            <% else %>
              <td>なし</td>
            <% end %>
            <% if ps.schedule_type.present? %>
              <td><%= ps.schedule_type %></td>
            <% else %>
              <td>なし</td>
            <% end %>
            <% if ps.comment_request.present? %>
              <td><%= ps.comment_request %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <td>
              <%= link_to pending_schedule_path(ps.id), method: :delete do %>
                <i class="fas fa-trash-alt fa-lg"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  <% else %>
    <p>未承認の日程申請はありません</p>
  <% end %>

  <br>
  <h3>承認・棄却済申請</h3>

  <p>■打刻申請</p>
  <% if @pending_timecards.exists?(status: ["承認","棄却"]) %>
    <table>
      <thead>
        <th>申請日</th>
        <th>対象日</th>
        <th>打刻種別</th>
        <th>申請された打刻</th>
        <th>申請者メッセージ</th>
        <th>承認者メッセージ</th>
        <th>承認状態</th>
      </thead>
      <% @pending_timecards.each do |pt| %>
        <% if pt.status != "未承認" %>
          <tr>
            <td><%= pt.created_at.strftime("%m/%d") %>(<%= day[pt.created_at.wday] %>)</td>
            <td><%= Day.find_by(id: Timecard.find_by(id: pt.timecard_id).day_id).date.strftime("%m/%d") %>(<%= day[Day.find_by(id: Timecard.find_by(id: pt.timecard_id).day_id).date.wday] %>)</td>
            <td><%= pt.timecard_type %></td>
            <% if pt.pending_time.present? %>
              <td><%= pt.pending_time.strftime("%R") %></td>
            <% else %>
              <td>--:--</td>
            <% end %>
            <% if pt.comment_request.present? %>
              <td><%= pt.comment_request %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <% if pt.comment_permission.present? %>
              <td><%= pt.comment_permission %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <td><%= pt.status %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  <% else %>
    <p>打刻申請履歴はありません</p>
  <% end %>

  <br>
  <p>■日程申請</p>
  <% if @pending_schedules.exists?(status: ["承認","棄却"]) %>
    <table>
      <thead>
        <th>申請日</th>
        <th>対象日</th>
        <th>申請された日程</th>
        <th>申請者メッセージ</th>
        <th>承認者メッセージ</th>
        <th>承認状態</th>
      </thead>
      <% @pending_schedules.each do |ps| %>
        <% if ps.status != "未承認" %>
          <tr>
            <td><%= ps.created_at.strftime("%m/%d") %>(<%= day[ps.created_at.wday] %>)</td>
            <td><%= Day.find_by(id: Schedule.find_by(id: ps.schedule_id).day_id).date.strftime("%m/%d") %>(<%= day[Day.find_by(id: Schedule.find_by(id: ps.schedule_id).day_id).date.wday] %>)</td>
            <% if ps.schedule_type.present? %>
              <td><%= ps.schedule_type %></td>
            <% else %>
              <td>なし</td>
            <% end %>
            <% if ps.comment_request.present? %>
              <td><%= ps.comment_request %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <% if ps.comment_permission.present? %>
              <td><%= ps.comment_permission %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <td><%= ps.status %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  <% else %>
    <p>日程申請履歴はありません</p>
  <% end %>

</div>